const Linkedin = ({size=18}) => <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-4 0v7h-4v-7a6 6 0 0 1 6-6z"/><rect x="2" y="9" width="4" height="12"/><circle cx="4" cy="4" r="2"/></svg>;
const timeline=[['2025','Innovis founded','A four-person engineering team began working with growing businesses from Sinnar, Maharashtra.'],['2025','First platforms shipped','Early client and venture products moved from prototypes into public use.'],['2026','AI workflow practice formed','The studio formalised its work in document automation, assisted search and operational AI.']];
const team=[
 ['YS','Yogesh Sadgir','Co-founder · Engineering','Leads technical strategy, platform architecture and full-stack delivery.','https://www.linkedin.com/in/yogesh-sadgir'],
 ['AP','Aniket Pangavhane','Co-founder · Product','Translates operational needs into coherent product and interface decisions.','https://www.linkedin.com/in/aniket-pangavhane'],
 ['OB','Om Bhavsar','Co-founder · AI systems','Builds applied machine-learning workflows and dependable data foundations.','https://www.linkedin.com/in/om-bhavsar'],
 ['KD','Karan Deshmukh','Co-founder · Partnerships','Connects delivery decisions with client outcomes and long-term relationships.','https://www.linkedin.com/in/karan-deshmukh']
];
export default function About(){return <><header className="compact-page-hero"><div className="container compact-page-hero-grid"><h1>About Innovis</h1><p>An independent product and engineering studio founded in Sinnar by four builders.</p></div></header><section className="section section--white"><div className="container story-grid"><div><p className="kicker">Our story</p><h2 className="section-title">Early, deliberately.</h2></div><div className="timeline">{timeline.map(t=><div className="timeline-item" key={t[1]}><span className="timeline-year">{t[0]}</span><div><h3>{t[1]}</h3><p>{t[2]}</p></div></div>)}</div></div></section><section className="section section--ink"><div className="container"><p className="kicker" style={{color:'var(--yellow)'}}>What we protect</p><div className="principles"><div className="principle"><h3>Clarity</h3><p>Say what the system does, what it cannot do, and what must be decided next.</p></div><div className="principle"><h3>Ownership</h3><p>The people making product decisions stay involved through production.</p></div><div className="principle"><h3>Usefulness</h3><p>A smaller tool used every day beats an impressive platform nobody trusts.</p></div></div></div></section><section className="section"><div className="container"><div style={{marginBottom:44}}><p className="kicker">Founding team</p><h2 className="section-title">Four disciplines, one table.</h2></div><div className="team-list">{team.map(([initials,name,role,bio,url])=><article className="team-member" key={name}><span className="initials">{initials}</span><div><h3>{name}</h3><small>{role}</small></div><a href={url} target="_blank" rel="noreferrer" aria-label={`${name} on LinkedIn`}><Linkedin size={18}/></a><p>{bio}</p></article>)}</div></div></section></>}


