import { useState } from 'react';
const studies=[
 {client:'RightVerse AI',title:'Making legal information easier to approach',problem:'Citizens lacked a clear route into everyday legal topics and basic rights.',solution:'We structured a plain-language content library with topical browsing and direct search.',results:[['3K+','monthly visitors'],['4.7 / 5','reported rating']],deep:'The platform combines a React interface with a structured content library covering civil, criminal and constitutional topics. Information architecture and search were prioritised so people could reach a relevant topic without already knowing the legal terminology.'},
 {client:'SnapShop AI',title:'Finding a product from a single image',problem:'Products seen on social media were difficult to locate and compare across stores.',solution:'We designed an image-led search flow that returns likely matches and purchase links.',results:[['Image in','one simple input'],['Multi-store','comparison']],deep:'The experience keeps a technically complex search process to one clear customer action. Results are organised for quick comparison, with the system doing the retrieval work behind the interface.'},
 {client:'Localify AI',title:'Shortening local-business research',problem:'Business discovery, contact research and outreach preparation were disconnected manual tasks.',solution:'We brought discovery, tracking and outreach preparation into one managed workflow.',results:[['One place','for the pipeline'],['Less rework','between steps']],deep:'Rather than presenting AI as a chat box, the product applies it inside a recognisable research workflow. Operators retain visibility over sources, prospects and prepared outreach.'},
 {client:'RK Tours & Travels',title:'Moving cab enquiries beyond phone calls',problem:'Manual coordination made customer enquiries slower and difficult to track.',solution:'We created a mobile-first booking enquiry and a lightweight operational view.',results:[['Mobile-first','booking flow'],['Clearer','request tracking']],deep:'The frontend focuses on the information a traveller needs to make a request, while the operational side gives the business a consistent record of incoming journeys and contact details.'}
];
export default function CaseStudies(){const[open,setOpen]=useState(null);return <><header className="compact-page-hero"><div className="container compact-page-hero-grid"><h1>Case Studies</h1><p>How operating constraints became useful, working products.</p></div></header><section className="section"><div className="container">{studies.map((s,i)=><article className="case-story" key={s.client}><span className="page-index">0{i+1}<br/>{s.client}</span><div><h2>{s.title}</h2><div className="case-detail">{s.results.map(r=><div className="case-result" key={r[0]}><strong>{r[0]}</strong><span className="muted">{r[1]}</span></div>)}</div></div><div><h3>The constraint</h3><p>{s.problem}</p><h3>What we changed</h3><p>{s.solution}</p></div><div className="case-expand"><button onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i}>{open===i?'Close project note':'Read the project note'}</button>{open===i&&<p className="case-deep">{s.deep}</p>}</div></article>)}</div></section></>}

