import { ArrowUpRight } from 'lucide-react';
const projects=[
 {name:'Genz',number:'01',category:'Beauty commerce',summary:'A refined personal-care storefront for discovering and buying perfumes, skincare and haircare essentials.',image:'/Genz.png',preview:'/GenzPreview.png',url:'https://genz-sepia-psi.vercel.app/',tone:'blue',built:['Commerce UX','Product discovery','Checkout flow']},
 {name:'RK Tours & Travels',number:'02',category:'Travel operations',summary:'A mobile-first enquiry and booking experience for a regional cab operator serving customers across India.',image:'/RK.png',preview:'/RKpreview.png',url:'https://rk-tours-travels.vercel.app',tone:'rose',built:['Booking UX','Mobile web','Operations workflow']},
 {name:'Innovis Billing',number:'03',category:'Business operations',summary:'A connected GST billing system for invoices, inventory, purchases, payments and reporting—online or offline.',image:'/Billing.png',preview:'/BillingPreview.png',url:'https://billing-three-dusky.vercel.app/',tone:'orange',built:['GST billing','Inventory control','Offline sync']},
 {name:'Localify AI',number:'04',category:'AI business discovery',summary:'A connected workflow for finding local businesses, organising verified contact data and preparing tailored outreach.',image:'/Localify.png',preview:'/Localifypreview.png',url:'https://localify-three.vercel.app',tone:'gold',built:['Product design','AI workflow','Full-stack engineering']},
 {name:'SnapShop AI',number:'05',category:'Visual commerce',summary:'An image-led search experience that turns a social-media product find into comparable places to buy.',image:'/SnapShop.png',preview:'/SnapShopPreview.png',url:'https://snapshop-ai-eta.vercel.app',tone:'orange',built:['Interface design','Visual search','Commerce integration']},
 {name:'RightVerse AI',number:'06',category:'Legal access',summary:'A plain-language legal information platform designed to make everyday rights easier for Indian citizens to understand.',image:'/RV.png',preview:'/RVpreview.png',url:'https://righ-verse.vercel.app',tone:'gold',built:['Information architecture','Search experience','Web platform']}
];
export default function Partners(){return <><header className="compact-page-hero"><div className="container compact-page-hero-grid"><h1>Clients & Partners</h1><p>Selected products delivered across beauty, billing, AI, travel, legal access and visual commerce.</p></div></header><section className="venture-list"><div className="container">{projects.map(p=><a href={p.url} target="_blank" rel="noreferrer" className={`venture-project venture-project--${p.tone}`} key={p.name}><div className="venture-art"><span>{p.number}</span><div className="client-preview-frame"><img className="client-preview" src={p.preview} alt={`${p.name} product preview`}/></div><span className="client-logo-badge"><img className="client-card-logo" src={p.image} alt="" aria-hidden="true"/></span><ArrowUpRight size={25}/></div><div className="venture-copy"><span>{p.category}</span><h2>{p.name}</h2><p>{p.summary}</p><div>{p.built.map(x=><small key={x}>{x}</small>)}</div></div></a>)}</div></section></>}
