import { ArrowUpRight } from 'lucide-react';
const projects=[
 {name:'Localify AI',number:'01',category:'AI business discovery',summary:'A connected workflow for finding local businesses, organising verified contact data and preparing tailored outreach.',image:'/Localify.png',url:'https://localify-three.vercel.app',tone:'blue',built:['Product design','AI workflow','Full-stack engineering']},
 {name:'SnapShop AI',number:'02',category:'Visual commerce',summary:'An image-led search experience that turns a social-media product find into comparable places to buy.',image:'/SnapShop.png',url:'https://snapshop-ai-eta.vercel.app',tone:'orange',built:['Interface design','Visual search','Commerce integration']},
 {name:'RightVerse AI',number:'03',category:'Legal access',summary:'A plain-language legal information platform designed to make everyday rights easier for Indian citizens to understand.',image:'/RV.png',url:'https://righ-verse.vercel.app',tone:'gold',built:['Information architecture','Search experience','Web platform']},
 {name:'RK Tours & Travels',number:'04',category:'Travel operations',summary:'A mobile-first enquiry and booking experience for a regional cab operator serving customers across India.',image:'/RK.png',url:'https://rk-tours-travels.vercel.app',tone:'rose',built:['Booking UX','Mobile web','Operations workflow']}
];
export default function Partners(){return <><header className="compact-page-hero"><div className="container compact-page-hero-grid"><h1>Clients & Partners</h1><p>Selected products delivered across AI, commerce, legal access and travel.</p></div></header><section className="venture-list"><div className="container">{projects.map(p=><a href={p.url} target="_blank" rel="noreferrer" className={`venture-project venture-project--${p.tone}`} key={p.name}><div className="venture-art"><span>{p.number}</span><img src={p.image} alt={p.name}/><ArrowUpRight size={25}/></div><div className="venture-copy"><span>{p.category}</span><h2>{p.name}</h2><p>{p.summary}</p><div>{p.built.map(x=><small key={x}>{x}</small>)}</div></div></a>)}</div></section></>}

