import { Link } from 'react-router-dom';
export default function Privacy(){
  const sections = [
    { title: '1. Information We Collect', content: `We collect information you provide directly to us when you use our services or contact us. This includes:\n\nâ€¢ **Contact Form Data**: Name, email address, company name, phone number, and message content when you submit an inquiry through our contact form.\nâ€¢ **Newsletter Subscriptions**: Email address when you subscribe to our newsletter.\nâ€¢ **Technical Data**: IP address, browser type, device information, and pages visited, collected automatically through standard web server logs.\nâ€¢ **Communication Data**: Records of correspondence if you contact us by email or phone.\n\nWe do not collect sensitive personal data such as payment information, government IDs, or biometric data through this website.` },
    { title: '2. How We Use Your Information', content: `Innovis IT Solutions uses the collected information for the following purposes:\n\nâ€¢ **Service Delivery**: To respond to your inquiries, provide requested information, and engage in business discussions.\nâ€¢ **Newsletter Communication**: To send periodic updates about our services, case studies, and technology insights (only with your explicit consent).\nâ€¢ **Service Improvement**: To analyze usage patterns and improve the functionality and content of our website.\nâ€¢ **Legal Compliance**: To comply with applicable laws, regulations, and legal processes.\nâ€¢ **Business Operations**: To protect the security and integrity of our services and prevent fraudulent activity.` },
    { title: '3. Sharing of Information', content: `We do not sell, rent, or trade your personal information to third parties. We may share your information only in the following limited circumstances:\n\nâ€¢ **Service Providers**: With trusted third-party vendors who assist in operating our website and delivering services (e.g., email delivery via Brevo/Sendinblue), bound by confidentiality obligations.\nâ€¢ **Legal Requirements**: When required by law, court order, or governmental authority.\nâ€¢ **Business Transfers**: In connection with a merger, acquisition, or sale of assets, with appropriate confidentiality protections.\nâ€¢ **With Your Consent**: In any other situation where you have given explicit consent.` },
    { title: '4. Data Retention', content: `We retain your personal information for as long as necessary to fulfil the purposes for which it was collected and to comply with legal obligations. Specifically:\n\nâ€¢ Contact form submissions are retained for 24 months from the date of submission.\nâ€¢ Newsletter subscription data is retained until you unsubscribe.\nâ€¢ Technical log data is retained for 90 days.\n\nYou may request deletion of your data at any time by contacting us at contact@innovis.com.` },
    { title: '5. Data Security', content: `Innovis IT Solutions implements industry-standard security measures to protect your information against unauthorized access, alteration, disclosure, or destruction. These include:\n\nâ€¢ TLS/SSL encryption for all data transmitted between your browser and our servers.\nâ€¢ Secure, access-controlled database systems hosted on cloud infrastructure.\nâ€¢ Regular security reviews and penetration testing of our systems.\n\nWhile we strive to protect your personal information, no method of electronic storage or transmission is 100% secure. We cannot guarantee absolute security.` },
    { title: '6. Cookies & Tracking', content: `Our website may use minimal cookies to improve your browsing experience. We do not use third-party advertising cookies or tracking pixels. The cookies we may use include:\n\nâ€¢ **Session Cookies**: Temporary cookies that are deleted when you close your browser.\nâ€¢ **Preference Cookies**: To remember your settings and preferences.\n\nYou can instruct your browser to refuse all cookies or indicate when a cookie is being sent. If you do not accept cookies, some portions of our website may not function properly.` },
    { title: '7. Your Rights', content: `Depending on your jurisdiction, you may have the following rights regarding your personal data:\n\nâ€¢ **Access**: Request a copy of the personal information we hold about you.\nâ€¢ **Rectification**: Request correction of inaccurate or incomplete information.\nâ€¢ **Erasure**: Request deletion of your personal information ("right to be forgotten").\nâ€¢ **Portability**: Request transfer of your data in a machine-readable format.\nâ€¢ **Objection**: Object to specific processing of your personal data.\nâ€¢ **Withdrawal of Consent**: Withdraw consent for newsletter communications at any time.\n\nTo exercise any of these rights, contact us at contact@innovis.com.` },
    { title: '8. Third-Party Links', content: `Our website may contain links to third-party websites, including our client and partner sites. These sites have their own privacy policies and are not governed by this Privacy Policy. We encourage you to review the privacy policies of any third-party sites you visit. Innovis IT Solutions is not responsible for the content or privacy practices of such sites.` },
    { title: '9. Changes to This Policy', content: `We may update this Privacy Policy from time to time to reflect changes in our practices or applicable law. We will post the updated policy on this page with a revised "Last Updated" date. We encourage you to review this page periodically. Continued use of our website after any changes constitutes acceptance of the updated policy.` },
    { title: '10. Contact Us', content: `If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:\n\nâ€¢ **Email**: contact@innovis.com\nâ€¢ **Phone**: +91 80879 59271\nâ€¢ **Address**: Innovis Pvt. Ltd., Sinnar, Maharashtra, India 422103` }
  ];
  const render=line=>({__html:line.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/^• /,'• ')});
  return <main className="legal"><div className="container--narrow"><p className="kicker">Legal</p><h1>Privacy policy</h1><p>Last updated: March 1, 2026</p><p>This policy explains what information Innovis collects through this website and how it is used.</p>{sections.map(sec=><section key={sec.title}><h2>{sec.title}</h2>{sec.content.split('\n').filter(Boolean).map((line,i)=><p key={i} dangerouslySetInnerHTML={render(line)}/>)}</section>)}<p style={{marginTop:50}}>Questions about your data? <Link className="text-link" to="/contact">Contact Innovis</Link></p></div></main>;
}
