import { Link } from 'react-router-dom';
export default function Terms(){
  const sections = [
    { title: '1. Acceptance of Terms', content: `By accessing or using the Innovis IT Solutions website (innovis.com) and any services offered therein, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using this website.\n\nThese Terms of Service apply to all visitors, users, and others who access or use the website. Innovis reserves the right to update these Terms at any time. Continued use of the website after any modification constitutes acceptance of the new terms.` },
    { title: '2. Services Description', content: `Innovis IT Solutions provides enterprise technology services including, but not limited to:\n\nâ€¢ Custom web and software development\nâ€¢ SaaS platform design and development\nâ€¢ Cloud infrastructure services (AWS, Azure, GCP)\nâ€¢ Cybersecurity consulting and implementation\nâ€¢ AI and automation engineering\nâ€¢ Data engineering and business intelligence\n\nSpecific service terms, deliverables, timelines, and pricing are governed by separate Service Agreements or Statements of Work (SOW) entered into between Innovis and each client.` },
    { title: '3. Intellectual Property', content: `The content on this website â€” including text, graphics, logos, images, and software â€” is the property of Innovis IT Solutions and is protected by applicable intellectual property laws.\n\nYou may not reproduce, distribute, modify, or create derivative works from any content on this website without express written permission from Innovis.\n\nClient work product, including custom software developed under a service agreement, is subject to the intellectual property provisions specified in the respective service contract. Unless otherwise agreed, upon full payment, clients receive a license to use the delivered software for their intended business purpose.` },
    { title: '4. User Conduct', content: `When using this website, you agree not to:\n\nâ€¢ Use the website for any unlawful purpose or in violation of any regulations.\nâ€¢ Attempt to gain unauthorized access to any part of the website or its systems.\nâ€¢ Transmit any malicious code, viruses, or disruptive software.\nâ€¢ Submit false or misleading information through contact forms.\nâ€¢ Engage in any activity that interferes with the proper functioning of the website.\nâ€¢ Use automated bots, scrapers, or crawlers without prior written consent.` },
    { title: '5. Limitation of Liability', content: `To the maximum extent permitted by applicable law, Innovis IT Solutions shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, this website or our services.\n\nThe website and its content are provided on an "as is" and "as available" basis without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement.\n\nOur total liability for any claim arising from the use of this website shall not exceed INR 1,000 (or equivalent currency).` },
    { title: '6. Third-Party Links', content: `Our website may contain links to third-party websites, including client and partner portals. These links are provided for your convenience only. Innovis does not endorse, control, or assume responsibility for the content, privacy policies, or practices of any third-party websites.\n\nWe encourage you to read the terms and privacy policies of any third-party websites you visit.` },
    { title: '7. Confidentiality', content: `Any information submitted through our contact forms or communicated to Innovis in the course of business discussions will be treated with professional confidentiality. We will not disclose your business requirements, technical challenges, or project details to third parties without your consent, except as required by law.\n\nFormal confidentiality obligations for engagements are governed by Non-Disclosure Agreements (NDAs) entered into prior to project commencement.` },
    { title: '8. Governing Law', content: `These Terms of Service shall be governed by and construed in accordance with the laws of India. Any disputes arising from these Terms or your use of this website shall be subject to the exclusive jurisdiction of the courts located in Nashik, Maharashtra, India.\n\nIf any provision of these Terms is found to be unenforceable, the remaining provisions shall continue in full force and effect.` },
    { title: '9. Contact Information', content: `For questions regarding these Terms of Service, please contact us:\n\nâ€¢ **Email**: contact@innovis.com\nâ€¢ **Phone**: +91 80879 59271\nâ€¢ **Address**: Innovis Pvt. Ltd., Sinnar, Maharashtra, India 422103` }
  ];
  const render=line=>({__html:line.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/^• /,'• ')});
  return <main className="legal"><div className="container--narrow"><p className="kicker">Legal</p><h1>Terms of service</h1><p>Last updated: March 1, 2026</p><p>These terms govern use of the Innovis website. Specific project work is governed by the relevant signed agreement.</p>{sections.map(sec=><section key={sec.title}><h2>{sec.title}</h2>{sec.content.split('\n').filter(Boolean).map((line,i)=><p key={i} dangerouslySetInnerHTML={render(line)}/>)}</section>)}<p style={{marginTop:50}}>Questions about these terms? <Link className="text-link" to="/contact">Contact Innovis</Link></p></div></main>;
}
